spring:
  data:
    mongodb:
      uri: mongodb+srv://bootcamp:eo4IaJNIbjk4f8ls@cluster0.hlzdcri.mongodb.net/movement?retryWrites=true&w=majority
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/banking-nttdata-bootcamp/movement
  application:
    name: movement
